<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?php echo $view->pageTitle; ?> - TreasureQuest</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="css/bootstrap.css" media="all">
        <!-- Custom styles for this template -->
        <link href="css/font-awesome.css" rel="stylesheet">
        <link href="css/main.css" rel="stylesheet">
    </head>
    <body>
        <?php require('template/header.phtml') ?>
        <main>
            <section>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-10">
                            <h1>Create Thread</h1>
                        </div>
                        <div class="col-md-1"></div>
                    </div> 
                </div>
            </section>
            <section>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-10">
                            <p> From: <?php echo htmlentities($view->authorName); ?></p>    
                        </div>
                        <div class="col-md-1"></div>
                    </div> 
                </div>
            </section>
            <section>
                <div class="container-fluid">
                    <div class="row">
                        <form method="post" enctype="multipart/form-data" id="formData" action="control.php?action=createNewThread">
                            <div class="form-group row">
                                <div class="col-sm-1"></div>
                                <label for="subject-input" class="col-sm-2 col-form-label">
                                    Thread Subject(*): 
                                </label>
                                <div class="col-sm-8">
                                    <input type="text" id="subject-input" name="subject" class="form-control" maxlength="50"/>                            
                                </div>
                                <div class="col-sm-1"></div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-1"></div>
                                <label for="content-input" class="col-sm-2 col-form-label">
                                    Initial Post(*): 
                                </label>
                                <div class="col-sm-8">
                                    <textarea name="content" id="content-input" class="form-control" maxlength="1000" rows="15"></textarea>                            
                                </div>
                                <div class="col-sm-1"></div>
                            </div>
                            <input type="hidden" name="author" value="<?php echo $view->sessionUsername; ?>">
                            <input type="hidden" name="replies">
                            <input type="hidden" name="views">
                            <input type="hidden" name="latestPost" value="This thread is new. Be the first one to comment!">
                            <input type="hidden" name="threadID">
                            <input type="hidden" name="username">
                            <input type="hidden" name="userAvatar" value="<?php echo $view->sessionAvatar; ?>">
                            <div class="form-group row"> 
                                <div class="col-sm-1"></div>
                                <div class="col-sm-10">
                                    <div class="flex-holder">
                                       <input name="submit" type="submit" class="btn btn-primary btn-lg btn-block hidden-print" value="Submit Details">
                                   </div>
                                </div>
                            </div> 
                        </form>    
                        <p>** - Compulsory fields</p>
                    </div>
                </div>
            </section>
        </main>
        <?php require('template/footer.phtml') ?>
        <script type="text/javascript">
            //Create a variable for storing the value of the php page's latitude variable
            var checkLat = '<?php echo $view->latitude; ?>';
            //Create a variable for storing the value of the php page's longitude variable
            var checkLng = '<?php echo $view->longitude; ?>';
            //Create a variable for storing the value of the php page's accuracy variable
            var checkAcc = '<?php echo $view->accuracy; ?>';

            //If the latitude, longitude and accuracy all equal false (i.e. if the user is not operating a mobile device and/or is logged off
            if (checkLat == false && checkLng == false && checkAcc == false) {
                //Do Nothing 
                //Otherwise, if the latitude, longitude and accuracy variables all equal true (i.e. if the user is operating a mobile device and is logged on)
            } else {
                //If the device picks up a location via router or radio mast
                if (navigator.geolocation) {
                    //Set up the location details in the followign function
                    navigator.geolocation.watchPosition(function (loc) {
                        //Create a form element for storing the location details
                        var userLocation = new Element('form', {
                            'id': 'userLocForm',
                            'name': 'userLocForm',
                            'action': '#',
                            'method': 'post'
                        });
                        //Create a hidden input variable for storing the location's latitude
                        new Element('input', {
                            'id': 'latitude',
                            'name': 'latitude',
                            'type': 'hidden',
                            'value': loc.coords.latitude
                        }).inject(userLocation);
                        //Create a hidden input variable for storing the location's longitude
                        new Element('input', {
                            'id': 'longitude',
                            'name': 'longitude',
                            'type': 'hidden',
                            'value': loc.coords.longitude
                        }).inject(userLocation);
                        //Create a hidden input variable for storing the location's accuracy
                        new Element('input', {
                            'id': 'accuracy',
                            'name': 'accuracy',
                            'type': 'hidden',
                            'value': loc.coords.accuracy
                        }).inject(userLocation);
                        //Create a request to send the form to the control.php page before calling it's userLocation method
                        var req = new Request.JSON({
                            url: 'control.php?action=userLocation',
                            onsuccess: ""
                        }).post(userLocation);
                        //Send the request
                        req.send();
                        //If the user chooses to share his/her location details
                        if (console)
                            console.log(loc);
                        //Perform the following function
                    }, function () {
                    }, {enableHighAccuracy: true});
                    //Otherwise, if the user chooses to not share his/her location details
                } else {
                    //Do Nothing
                }
            }
        </script>
        <script src="js/jquery.js"></script>
        <script src="js/popper.js"></script>
        <script src="js/bootstrap.js"></script>  
        <script type="text/javascript">
            jQuery(function ($) {
                $.noConflict();
                $(document).ready(function () {
                    //Variable for referencing the input field whose name equals "subject"
                    var $subject = $('input[name="subject"]');
                    //Variable for referencing the input field whose name equals "content"
                    var $content = $('input[name="content"]');
                    //Variable for referencing the input field whose name equals "author"
                    var $huntName = $('input[name="author"]');
                    //Create a variable by getting the html div whose id is "newThreadForm" from the body
                    var $formDiv = $('#newThreadForm');
                    //
                    $formDiv.submit(function (e) {
                        //If the session ID (represented as a local php variable) have been deleted
                        if ('<?php echo $view->sessionID; ?>' === "") {
                            //Redirect to the login page
                            window.location = 'login.php';
                            //Otherwise, if either of the IDs have been found
                        } else {
                            //Stop page refresh
                            e.stop();
                            //Create a boolean ticket variable with a default value of true
                            var ticket = true;
                            //If the subject text box element is empty
                            if ($subject.value === "") {
                                //Change the ticket value to false
                                ticket = false;
                                //Change the color of the text box to red
                                $subject.css("backgroundColor", "red");
                                //If not
                            } else {
                                //Change the color of the text box to white
                                $subject.css("backgroundColor", "white");
                            }
                            //If the initial reply textarea element is empty
                            if ($content.value === "") {
                                //Change the ticket value to false
                                ticket = false;
                                //Change the color of the textarea to red
                                $content.css("backgroundColor", "red");
                                //If not
                            } else {
                                //Change the color of the textarea to white
                                $content.css("backgroundColor", "white");
                            }
                            //If the ticket value has been changed to false
                            if (ticket === "false") {
                                //Do nothing
                                //Otherwise, if the ticket value has been changed to true
                            } else if (ticket === "true") {
                                //Submit the form using AJAX.
                                $.ajax({
                                    //Set the type to "POST"
                                    type: 'POST',
                                    //Set the destination url as the form's action
                                    url: $formDiv.attr('action'),
                                    //Set the data to be sent as the data array defined before
                                    data: $formDiv.serialize()
                                            //data: new FormData($formData)
                                }).done(function (response) {
                                    //Once successful, redirect to the messageSent page
                                    window.location.href = "userForumTopics.php";
                                });
                            }
                        }
                    });
                });
            });
        </script>
    </body>
</html>