<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?php echo $view->pageTitle; ?> - TreasureQuest</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="css/bootstrap.css" media="all">
        <!-- Custom styles for this template -->
        <link href="css/font-awesome.css" rel="stylesheet">
        <link href="css/main.css" rel="stylesheet">
    </head>
    <body>
        <?php require('template/header.phtml') ?>
        <main>
            <section>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-10">
                            <h1><strong><?php echo htmlentities($view->threadSubject); ?></strong></h1>
                        </div>
                        <div class="col-md-1"></div>
                    </div> 
                </div>
            </section>
            <?php if ($view->threadExists == "true") : ?>
            <section>
                <?php foreach ($view->repliesList as $reply) : ?>
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-1"></div>
                                <div class="col-md-10">
                                    <table class="table table-bordered table-responsive">
                                        <tr><td>Reply from <?php echo htmlentities($reply->getUsername()); ?> at <?php echo htmlentities($reply->getDate()); ?></td></tr>
                                        <tr>
                                            <td> 
                                                <img src='<?php echo htmlentities($reply->getUserAvatar()); ?>' style="width:60px; height:120px" alt="user-avatar">
                                            </td>
                                            <td><?php echo htmlentities($reply->getContent()); ?></td>
                                        </tr>        
                                        <?php if ($view->sessionUsername == $reply->getUsername() || $view->sessionUserStatus == "Admin") : ?> 
                                            <tr>
                                                <td>
                                                    <form action="#" method="post">
                                                        <input name="id" type="hidden" value="<?php echo htmlentities($reply->getId()); ?>">
                                                        <input name="delete" type="submit" value="DELETE YOUR REPLY" />
                                                    </form>
                                                </td>
                                            </tr>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </table>
                            </div>
                            <div class="col-md-1"></div>
                        </div> 
                    </div>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-1"></div>
                            <div class="col-md-10">
                                <?php echo htmlentities($view->message); ?>
                                <?php if ($view->sessionUsername != null || $view->sessionPassword != null) : ?>
                                    <form action="#" method="post">
                                        <input name="threadID" type="hidden" value="<?php echo htmlentities($view->threadID); ?>"/>
                                        <input name="username" type="hidden" value="<?php echo htmlentities($view->sessionUsername); ?>"/>
                                        <input name="userAvatar" type="hidden" value="<?php echo htmlentities($view->sessionAvatar); ?>"/>
                                        <input name="threadTitle" type="hidden" value="<?php echo htmlentities($view->threadSubject); ?>"/>
                                        <textarea name="content" rows="20" cols="40"/></textarea>
                                        <br/>
                                        <input name="submit" type="submit" value="INSERT NEW REPLY" />
                                    </form>
                                <?php endif; ?>
                            </div>
                            <div class="col-md-1"></div>
                        </div> 
                    </div>
                </section>
            <?php endif; ?>
        </main>
        <?php require('template/footer.phtml') ?>
        <script type="text/javascript">
            //Create a variable for storing the value of the php page's latitude variable
            var checkLat = '<?php echo $view->latitude; ?>';
            //Create a variable for storing the value of the php page's longitude variable
            var checkLng = '<?php echo $view->longitude; ?>';
            //Create a variable for storing the value of the php page's accuracy variable
            var checkAcc = '<?php echo $view->accuracy; ?>';

            //If the latitude, longitude and accuracy all equal false (i.e. if the user is not operating a mobile device and/or is logged off
            if (checkLat == false && checkLng == false && checkAcc == false) {
                //Do Nothing 
                //Otherwise, if the latitude, longitude and accuracy variables all equal true (i.e. if the user is operating a mobile device and is logged on)
            } else {
                //If the device picks up a location via router or radio mast
                if (navigator.geolocation) {
                    //Set up the location details in the followign function
                    navigator.geolocation.watchPosition(function (loc) {
                        //Create a form element for storing the location details
                        var userLocation = new Element('form', {
                            'id': 'userLocForm',
                            'name': 'userLocForm',
                            'action': '#',
                            'method': 'post'
                        });
                        //Create a hidden input variable for storing the location's latitude
                        new Element('input', {
                            'id': 'latitude',
                            'name': 'latitude',
                            'type': 'hidden',
                            'value': loc.coords.latitude
                        }).inject(userLocation);
                        //Create a hidden input variable for storing the location's longitude
                        new Element('input', {
                            'id': 'longitude',
                            'name': 'longitude',
                            'type': 'hidden',
                            'value': loc.coords.longitude
                        }).inject(userLocation);
                        //Create a hidden input variable for storing the location's accuracy
                        new Element('input', {
                            'id': 'accuracy',
                            'name': 'accuracy',
                            'type': 'hidden',
                            'value': loc.coords.accuracy
                        }).inject(userLocation);
                        //Create a request to send the form to the control.php page before calling it's userLocation method
                        var req = new Request.JSON({
                            url: 'control.php?action=userLocation',
                            onsuccess: ""
                        }).post(userLocation);
                        //Send the request
                        req.send();
                        //If the user chooses to share his/her location details
                        if (console)
                            console.log(loc);
                        //Perform the following function
                    }, function () {
                    }, {enableHighAccuracy: true});
                    //Otherwise, if the user chooses to not share his/her location details
                } else {
                    //Do Nothing
                }
            }
        </script>
        <script src="js/jquery.js"></script>
        <script src="js/popper.js"></script>
        <script src="js/bootstrap.js"></script>  
    </body>
</html>