<footer class="footer-main hidden-print">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12" id="footer">
                <p>*** TreasureQuest.com - Est. 24/10/2012 ***</p> 
                <a href="http://jigsaw.w3.org/css-validator/check/referer">
                    <img style="border:0;width:88px;height:31px"
                         src="http://jigsaw.w3.org/css-validator/images/vcss"
                         alt="Valid CSS!" />
                </a> 
            </div>
        </div>
    </div>
</footer>