<header>
    <a href="index.php"><img class="banner-image" src="images/WebsiteLogo.JPG" alt="Treasure Quest Logo" /></a>
    <nav class="navbar navbar-expand-md navbar-dark hidden-print">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="login.php">LOGIN</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="huntListing.php">HUNTS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="userForumTopics.php">USER FORUM</a>
                </li>   
            </ul>
        </div>  
    </nav>
</header>